const FIELD_MAPPINGS_CSV = {
  "OrderID*": "orderId",
  "Order Date": "orderDate",
  "Fulfilment Date": "fulfilmentDate",
  "Shipper*(Shipping Name)": "shippingName",
  "Company": "company",
  "Contact Name*": "contactName",
  "tracking": "tracking",
  "Address 1**": "address1",
  "Address 2": "address2",
  "City*": "city",
  "State": "state",
  "Zip Code": "zipCode",
  "Country Code* (2-letter)": "countryCode",
  "Phone*": "phone",
  "Email": "email",
  "Total  Quantity*": "totalQuantity",
  "Total Value (in USD)": "totalValueUSD",
  "Insurance Value (in USD)": "insuranceValueUSD",
  "Service*": "service",
  "Tax Paid By (DDU/ DDP)": "taxPaidBy",
  "Customes Description Override": "customsDescriptionOverride",
  "Tracking number": "trackingNumber",
  "Tracking status": "trackingStatus",
  "Parcel weight (kg) ": "parcelWeightKg",
  "Parcel weight (lbs)": "parcelWeightLbs",
  "Parcel height (cm)": "parcelHeightCm",
  "Parcel height (in)": "parcelHeightIn",
  "Parcel width (cm)": "parcelWidthCm",
  "Parcel width (in)": "parcelWidthIn",
  "Parcel length (cm) ": "parcelLengthCm",
  "Parcel length (in) ": "parcelLengthIn",
  "Dim Weight": "dimWeight",
  "Pick/Pack fee": "pickPackFee",
  "Actual Cost": "actualCost",
  "Actual weight": "actualWeight",
  "Batch number": "batchNumber",
  "Warehouse": "warehouse",
  "Client Purchase Order": "clientPurchaseOrder",
};

module.exports = { FIELD_MAPPINGS_CSV };
